services:
  vodolei:
    image: flask-app
    ports:
      - 5000:5000
    volumes:
      - ./src:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000